# Generated by Django 6.0.2 on 2026-02-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_bookings_created_at_bookings_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="distance_km",
            new_name="final_price",
        ),
    ]
